name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checout repo
              uses: actions/checkout@v4

            - name: welcome message
              run: echo "welcome to my first github"

            - name: list files
              run: ls

            - name: read file
              run: cat README.md