name: generate acsii

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: install cowsay programm
          run: sudo apt-get install cowsay -y

        - name: execute the cowsay cmd
          run: cowsay -f dragon "run for cover" >> dragon.txt

        - name: test file exists
          run: grep -i cover dragon.txt

        - name: read file
          run: cat dragon.txt


        - name: list repo files
          run: ls -lrth